import Head from 'next/head'
import {GetStaticProps} from "next"
import {useState} from "react"

import {Button, Htag, Input, Paragraph, Rating, Tag, TextArea} from "src/components"
import {MenuItem} from "src/interfaces/menu.interface"
import {withLayout} from "src/layout"

import axios from 'axios'
import {API} from "src/helpers/api";


const Home = ({menu, firstCategory}: HomeProps) => {
  const [rating, setRating] = useState(3)

  return (
    <>
      <Head>
        <title>Top App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Htag tag="h3">hello world</Htag>
      <Button appearance="primary" arrow="down">button</Button>
      <Button appearance="ghost" arrow="right">button</Button>
      <Paragraph size="large">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, ipsa?</Paragraph>
      <Paragraph size="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, ipsa?</Paragraph>
      <Paragraph size="medium">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, ipsa?</Paragraph>

      <Tag>hh.ru</Tag>
      <Tag color="green">hh.ru</Tag>
      <Tag color="gray">hh.ru</Tag>
      <Tag color="red">hh.ru</Tag>

      <Rating rating={rating} setRating={setRating} isEditable={true}/>

      <ul>
        {
          menu.map(m => (
            <li key={m._id.secondCategory}>{m._id.secondCategory}</li>
          ))
        }
      </ul>

      <Input placeholder="Name"/>
      <TextArea placeholder="woeiwoeio"/>
    </>
  )
}

export default withLayout(Home)

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const firstCategory = 0

  const {data: menu} = await axios.post<MenuItem[]>(
    API.topPage.find,
    {firstCategory}
  )

  return {
    props: {
      menu,
      firstCategory,
    }
  }
}


interface HomeProps extends Record<string, unknown> {
  menu: MenuItem[]
  firstCategory: number
}